name: "Publish - Development"

# This will trigger the action on each push to the `release` branch.
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - name: Rust Dependency Cache
        uses: Swatinem/rust-cache@v2

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf capnproto libasound2-dev

      - name: install homebrew (OSX only)
        if: matrix.platform == 'macos-latest'
        uses: Homebrew/actions/setup-homebrew@master

      - name: install dependencies (OSX only)
        if: matrix.platform == 'macos-latest'
        run: |
          brew install capnp

      - name: install dependencies (Windows only)
        if: matrix.platform == 'windows-latest'
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install capnproto

      - name: install frontend dependencies
        run: pnpm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: Dev release ${{ github.sha }} - ${{ matrix.platform }}
          path: src-tauri/target/release/bundle
